services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecureRootPW_82#kl
      MYSQL_DATABASE: app_database
      MYSQL_USER: appuser
      MYSQL_PASSWORD: :X=F.t@s*xK}q>c#6quW
      TZ: America/Toronto
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1g
  api:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g
    restart: unless-stopped
    build:
      context: .
      dockerfile: nest/Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - ./nest/.env
    environment:
      DB_SEED: true
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: appuser
      DB_PASSWORD: :X=F.t@s*xK}q>c#6quW
      DB_DATABASE: app_database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: America/Toronto
    depends_on:
      - db
      - redis
    volumes:
      - ./nest/upload:/api/nest/upload
      - ./nest/logs:/api/nest/logs
      - ./nest/public:/api/nest/public
      - ./nest/certs:/api/nest/certs
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: America/Toronto
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
    restart: unless-stopped
  web:
    container_name: web
    build:
      context: .
      dockerfile: vue/Dockerfile
    command: echo "Build complete"
    # volumes:
    #   - ./vue/dist:/usr/share/nginx/html:ro
  nginx:
    image: lumina-full-stack-template-web:latest
    container_name: nginx
    ports:
      - "8080:8080"
    environment:
      TZ: America/Toronto
    depends_on:
      - api
      - web
    volumes:
      - ./vue/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vue/certs:/etc/nginx/certs:ro
    # - ./vue/dist:/usr/share/nginx/html:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m
    restart: unless-stopped
volumes:
  redis-data:
  db-data:
