# ---------- build stage ----------
FROM node:20-bookworm-slim AS build
WORKDIR /web

COPY vue/package*.json ./vue/
WORKDIR /web/vue
RUN npm ci

WORKDIR /web

COPY tsconfig*.json ./
COPY library ./library
COPY vue ./vue

WORKDIR /web/vue
RUN npm run build

# ---------- runtime stage ----------
FROM nginx:1.27-alpine AS runner

COPY --from=build /web/vue/dist /usr/share/nginx/html
COPY vue/nginx.conf /etc/nginx/conf.d/default.conf
COPY vue/certs ./certs

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]